import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "XT Clicker",
  description: "Generated by Tascbar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased grainy`}>{children}</body>
    </html>
  );
}
